using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Botany;

[GenerateTypedNameReferences]
public sealed partial class SeedSplicerMenu : FancyWindow
{
    public SeedSplicerMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void Update(Entity<SeedSplicerComponent> ent)
    {
        if (ent.Comp.SeedSlotLeft.Item != null)
            SeedSpriteLeft.SetEntity(ent.Comp.SeedSlotLeft.Item);
        if (ent.Comp.SeedSlotRight.Item != null)
            SeedSpriteRight.SetEntity(ent.Comp.SeedSlotRight.Item);
    }

}
