using Content.Client.UserInterface.Controls;
using Content.Shared._Funkystation.Botany;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Funkystation.Botany;

[GenerateTypedNameReferences]
public sealed partial class SeedSplicerMenu : FancyWindow
{
    [Dependency] private IEntityManager _entityManager = default!;
    private EntityUid _owner;

    public SeedSplicerMenu()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetEntity(EntityUid owner)
    {
        _owner = owner;
        UpdateUi();
    }

    public void UpdateUi()
    {
        if (!_entityManager.TryGetComponent<SeedSplicerComponent>(_owner, out var seedSplicer))
            return;

        //TODO: Botany refactor: Use actual seed names
        if (seedSplicer.SeedSlotLeft.Item != null)
        {
            SeedSpriteLeft.SetEntity(seedSplicer.SeedSlotLeft.Item);
            SeedLabelLeft.Text = seedSplicer.SeedSlotLeft.ID;
        }
        else
        {
            SeedSpriteLeft.SetEntity(null);
            SeedLabelLeft.Text = "no seed loaded";
        }

        if (seedSplicer.SeedSlotRight.Item != null)
        {
            SeedSpriteRight.SetEntity(seedSplicer.SeedSlotRight.Item);
            SeedLabelRight.Text = seedSplicer.SeedSlotRight.ID;
        }
        else
        {
            SeedSpriteRight.SetEntity(null);
            SeedLabelRight.Text = "no seed loaded";
        }
    }

}
